output: web
timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

url: https://redhat-appstudio.github.io/appstudio.docs.ui.io/

format: web


target: web

lang: en_US

