output: web
timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

site.url: https://redhat-appstudio.github.io/stonesoup.doc.ui.io/

format: web


target: web

lang: en_US

